### ISSUE TITLE
[Suggestion] Change backpack storage to UUID

### ISSUE THREAD

**Issue by BlazenFury908** [PluginBugs/Issues-EpicBackpacks#21]
I really like the plugin, but I would really like if personal backpacks were stored with UUIDs because when a player changes their name, their personal backpack gets wiped.

**Comment by Pyario** [comment]
@LoneDev6
I hope he'll add it soon, it shouldn't be that difficult! :)

**Comment by LoneDev6** [comment]
This is totally planned.
Sadly I coded this plugin part in 2016 when it wasn't really common to use UUID to save data.

It's not really easy since I have to make sure old files still work after the update.
I'll try to find a solution, thanks.

Anyway a complete recode of the plugin is planned and this means I'll add a LOT of new features to justify the price of the plugin.

**Comment by LoneDev6** [comment]
UUID support is now implemented.
NOTE: old backpacks should load fine but might have some issues loading in some rare cases.
