### ISSUE TITLE
Option to make backpacks unstackable

### ISSUE THREAD

**Issue by NiceKaleido** [PluginBugs/Issues-EpicBackpacks#95]
**Is your feature request related to a problem? Please describe.**
It kind of is. Players are able to stack up empty backpacks or backpacks with the exact same items. Therefore they're unable to take single ones out of inventory when they reached the max limit of backpacks

**Describe the solution you'd like**
An option to make backpacks unstackable in general. 

**Describe alternatives you've considered**
none

**Comment by LoneDev6** [comment]
Players should not be able to craft identical backpacks, EBP plugin has a logic to prevent creating identical backpacks items so they won't stack.
Did you increase the stack size manually using a plugin? For example Essentials command `/more`?

**Comment by LoneDev6** [comment]
After some tests I managed to document why it's not possible to implement the anti stack on crafting.
The issue is that the game doesn't provide a method to know how many items are crafted using SHIFT-CLICK, this limit doesn't make apply anti-stack ID to each single result item without causing duplication issues.


Your players have to separate the stacked backpacks and open 1 single one at a time as stacks with more than 1 item won't open.
